<a href="https://colab.research.google.com/github/HemanthKumarA12/Natual_language_Processing/blob/master/keras_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import  load_iris

In [3]:
iris= load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X= iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y= iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from keras.utils import  to_categorical

In [11]:
y= to_categorical(y)

In [12]:
y.shape

(150, 3)

In [13]:
from sklearn.model_selection import  train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
from sklearn.preprocessing import  MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()


In [17]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_trained = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
from keras.models import  Sequential
from keras.layers import  Dense

In [23]:
model = Sequential()
model.add(Dense(8, input_dim=4 ,activation='relu'))
model.add(Dense(8, input_dim=4 ,activation='relu'))
model.add(Dense(3, activation='softmax' ))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(scaled_X_trained, y_train ,epochs=150, verbose=2)

Epoch 1/150
 - 2s - loss: 1.2043 - accuracy: 0.3500
Epoch 2/150
 - 0s - loss: 1.1901 - accuracy: 0.3500
Epoch 3/150
 - 0s - loss: 1.1774 - accuracy: 0.3500
Epoch 4/150
 - 0s - loss: 1.1660 - accuracy: 0.3500
Epoch 5/150
 - 0s - loss: 1.1543 - accuracy: 0.3500
Epoch 6/150
 - 0s - loss: 1.1465 - accuracy: 0.3500
Epoch 7/150
 - 0s - loss: 1.1381 - accuracy: 0.3500
Epoch 8/150
 - 0s - loss: 1.1319 - accuracy: 0.3500
Epoch 9/150
 - 0s - loss: 1.1257 - accuracy: 0.3500
Epoch 10/150
 - 0s - loss: 1.1204 - accuracy: 0.3600
Epoch 11/150
 - 0s - loss: 1.1145 - accuracy: 0.3600
Epoch 12/150
 - 0s - loss: 1.1091 - accuracy: 0.3500
Epoch 13/150
 - 0s - loss: 1.1039 - accuracy: 0.3100
Epoch 14/150
 - 0s - loss: 1.0991 - accuracy: 0.3000
Epoch 15/150
 - 0s - loss: 1.0949 - accuracy: 0.3200
Epoch 16/150
 - 0s - loss: 1.0913 - accuracy: 0.3200
Epoch 17/150
 - 0s - loss: 1.0875 - accuracy: 0.3500
Epoch 18/150
 - 0s - loss: 1.0839 - accuracy: 0.3800
Epoch 19/150
 - 0s - loss: 1.0800 - accuracy: 0.4000
Ep

In [26]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [27]:
model.predict(scaled_X_test)

array([[2.5801366e-02, 5.5874586e-01, 4.1545275e-01],
       [9.5508230e-01, 4.3669656e-02, 1.2480753e-03],
       [2.1627134e-04, 1.1300145e-01, 8.8678223e-01],
       [2.8137438e-02, 5.2554262e-01, 4.4631994e-01],
       [1.0033442e-02, 4.4716015e-01, 5.4280639e-01],
       [9.2664516e-01, 7.0053138e-02, 3.3017239e-03],
       [1.2670001e-01, 6.3545144e-01, 2.3784848e-01],
       [2.9756271e-03, 2.5259987e-01, 7.4442452e-01],
       [4.3719164e-03, 2.3751605e-01, 7.5811201e-01],
       [5.7474177e-02, 5.9151870e-01, 3.5100707e-01],
       [9.2029264e-03, 3.9540374e-01, 5.9539330e-01],
       [9.2444927e-01, 7.1374267e-02, 4.1765086e-03],
       [9.5378381e-01, 4.4673029e-02, 1.5431520e-03],
       [9.2873514e-01, 6.7669310e-02, 3.5955103e-03],
       [9.6619540e-01, 3.2972805e-02, 8.3186256e-04],
       [4.4749718e-02, 6.2739098e-01, 3.2785919e-01],
       [1.4859823e-03, 1.9917487e-01, 7.9933918e-01],
       [4.7585160e-02, 5.5583638e-01, 3.9657843e-01],
       [3.8705215e-02, 5.703

In [28]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [29]:
predictions = model.predict_classes(scaled_X_test)

In [30]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [31]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [33]:
from sklearn.metrics import  classification_report,accuracy_score, confusion_matrix

In [34]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]])

In [35]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [36]:
model.save('mymodel.h5')

In [37]:
from keras.models import  load_model

In [38]:
new_model= load_model('mymodel.h5')

In [39]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])